version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: dev-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: webhooks
    ports:
      - 27017:27017
    volumes:
      - .mongo/:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  rabbitmq:
#    image: rabbitmq:3.8
    build:
      context: .docker/rabbit
      dockerfile: ./Dockerfile
    container_name: dev-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: 'rabbitmq'
    #volumes:
      #- './enabled_plugins:/etc/rabbitmq/enabled_plugins'
      #- './rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro'
      #- './autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez'
