version: '2'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - '3333:3333'
    depends_on:
      - subscribe-service
      - webhook-sender
  subscribe-service:
    build:
      context: .
      dockerfile: apps/subscribe-service/Dockerfile
    container_name: subscribe-service
    depends_on:
      - mongodb
  webhook-sender:
    build:
      context: .
      dockerfile: apps/webhook-sender/Dockerfile
    container_name: webhook-sender
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: webhooks
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    labels:
      NAME: 'rabbitmq'
      #volumes:
      #- './enabled_plugins:/etc/rabbitmq/enabled_plugins'
      #- './rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro'
      #- './autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez'

volumes:
  mongodb-data: {}
